### PR TITLE
Have 75 books inscribed, contact me at @Jiurn or @Geckoking_ on X please, wanna talk and is very interested

### PR DESCRIPTION
**Pull request by Jiurn**
Hello,

My name is Jiurn, and I’m genuinely excited about the work you’ve done here. I have more than 75 inscribed books that I believe could be valuable additions to this project. Before contributing further, I’d love the opportunity to discuss these with you directly.

Since I wasn’t sure of another way to reach out, I’ve created this PR to get in touch. I apologize for any inconvenience this might cause. Please feel free to contact me on X (Twitter) at @Jiurn or @Geckoking_.

Thank you so much for your time, and feel free to close or delete this PR after reading. I look forward to hearing from you.

Best regards,
Jiurn

### CODE REVIEW

**Comment by etching-net** [comment]
> My name is Jiurn, and I’m genuinely excited about the work you’ve done here. I have more than 75 inscribed books that I believe could be valuable additions to this project.

Dear Jiurn, thank you for inscribing books! You are most welcome to add to this index any and all works with longstanding cultural value.

**Comment by Jiurn** [comment]
Dear etching,

Thank you for your answer and for everything you have done, it’s truly
splendid work. We are doing something very similar with Inscripedia.com, my
company. We aim to become the library of Alexadria on Bitcoin where we give
a frictionless access to every text inscribed on Bitcoin and your work in
invaluable in helping us achieving our goal. On our end, we inscribed a lot
of books like Sherlock Holmes, Frankenstein, a tale of 2 cities, Peter pan,
A scarlet letter and much, much more.

I was wondering if we could acquire some of the texts you’ve inscribed? It
would be part of a marketing strategy to make written inscriptions popular
on Bitcoin and drive attention on the book ecosystem on Bitcoin which is
currently relatively non-existent.

Thank you for your time and wishing you a great day ahead,

Jiurn

**Comment by etching-net** [comment]
There are no plans to move or monetize any inscriptions connected with this project, but I appreciate the offer and kind words. Please do cross-pollinate by advertising on this index the inscriptions of books like those you mentioned, and best of luck with Inscripedia!

**Comment by Jiurn** [comment]
No problem.

Can we use your inscriptions and make them free mint/open edition on
Inscripedia so anyone can get their own copy of the stories/books? I’m sure
many people would like to have their own free copy of the prince and other
classics. We would use delegate technology to do this. It would have been
nice to use parent child and create a “first edition”, but we will respect
your wishes. Again, thank you very mich for the work you did!

Best regards,

Jiurn

**Pull request closed without merging**
